name: Install Dependencies
description: Install package dependencies using uv

inputs:
  options:
    description: 'Package options to install (space-separated, e.g., "full"). "none is an alias for empty string.'
    required: false
    default: 'full'
  groups:
    description: 'Dependency groups to install (space-separated, e.g., "test doc")'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Install dependencies (options=[${{ inputs.options }}], groups=[${{ inputs.groups }}])
      shell: bash
      run: |
        # Handle "none" as alias for empty string
        options_input="${{ inputs.options }}"
        if [ "$options_input" = "none" ]; then
          options_input=""
        fi

        # Build the install command
        cmd="uv pip install -e"

        # Add options if provided
        if [ -n "$options_input" ]; then
          # Convert space-separated options to comma-separated for brackets
          options=$(echo "$options_input" | tr ' ' ',')
          cmd="$cmd '.[$options]'"
        else
          cmd="$cmd ."
        fi

        # Add groups
        for group in ${{ inputs.groups }}; do
          cmd="$cmd --group $group"
        done

        # Execute the command
        eval $cmd
