name: Install Dependencies
description: Install package dependencies using uv

inputs:
  options:
    description: 'Package options to install (space-separated, e.g., "full").'
    required: false
    default: 'full'
  groups:
    description: 'Dependency groups to install (space-separated, e.g., "test doc")'
    required: false
    default: ''

runs:
  using: composite
  steps:
    - name: Install dependencies (options=[${{ inputs.options }}], groups=[${{ inputs.groups }}])
      shell: bash
      run: |
        # Build the install command
        cmd="uv pip install -e"

        # Convert space-separated options to comma-separated for brackets
        # E.g. "abc def" => '.[abc,def]'
        options=$(echo "${{ inputs.options }}" | tr ' ' ',')
        cmd="$cmd '.[$options]'"

        # Add groups
        for group in ${{ inputs.groups }}; do
          cmd="$cmd --group $group"
        done

        # Execute the command
        eval $cmd
