name: Setup uv
description: Setup uv with caching enabled

inputs:
  python-version:
    description: 'Python version to use'
    required: false
    default: '3.14'

runs:
  using: composite
  steps:
    - name: Set up uv
      uses: astral-sh/setup-uv@v5
      with:
        python-version: ${{ inputs.python-version }}
        enable-cache: true
        cache-dependency-glob: "**/pyproject.toml"
