from .aligned_mtl import AlignedMTL
from .bases import Aggregator
from .cagrad import CAGrad
from .constant import Constant
from .dualproj import DualProj
from .graddrop import GradDrop
from .imtl_g import IMTLG
from .krum import Krum
from .mean import Mean
from .mgda import MGDA
from .nash_mtl import NashMTL
from .pcgrad import PCGrad
from .random import Random
from .sum import Sum
from .trimmed_mean import TrimmedMean
from .upgrad import UPGrad
