from torchjd.aggregation.aligned_mtl import AlignedMTL
from torchjd.aggregation.bases import Aggregator
from torchjd.aggregation.cagrad import CAGrad
from torchjd.aggregation.constant import Constant
from torchjd.aggregation.dualproj import DualProj
from torchjd.aggregation.graddrop import GradDrop
from torchjd.aggregation.imtl_g import IMTLG
from torchjd.aggregation.krum import Krum
from torchjd.aggregation.mean import Mean
from torchjd.aggregation.mgda import MGDA
from torchjd.aggregation.nash_mtl import NashMTL
from torchjd.aggregation.pcgrad import PCGrad
from torchjd.aggregation.random import Random
from torchjd.aggregation.sum import Sum
from torchjd.aggregation.trimmed_mean import TrimmedMean
from torchjd.aggregation.upgrad import UPGrad
