name: Run Tests
description: Run unit and doc tests with coverage

inputs:
  dtype:
    description: 'Torch dtype to use for tests'
    required: false
    default: 'float32'
  device:
    description: 'Torch device to use for tests'
    required: false
    default: 'cpu'

runs:
  using: composite
  steps:
    - name: Run unit and doc tests with coverage report
      shell: bash
      env:
        PYTEST_TORCH_DTYPE: ${{ inputs.dtype }}
        PYTEST_TORCH_DEVICE: ${{ inputs.device }}
      run: |
        uv run pytest -W error tests/unit tests/doc --cov=src --cov-report=xml
